### PR TITLE
TrxTestResultXmlParser can read more result types

### LINKED ISSUE #74: xml file doesn't have all the details which it suppose to be, it looks quite  empty
@gfoidl 
I too noticed that the converted file is quite empty. 
And my need is to convert the file of trx and import it to QMetry  (addon to Jira). They provided some sample xml which they are supporting. 
Now, I need to make sure the converted file should be quite similar to QMetry file else it would not get imported. So, i shared it with you as the converted xml file was looking empty.

_Originally posted by @jsingh-qualitrol in https://github.com/gfoidl/trx2junit/pull/69#issuecomment-644331653_

### PR DESCRIPTION
**Pull request by gfoidl**
The following result types are now "understood":

* UnitTestResult (as previous)
* TestResultAggregation
* GenericTestResult
* TestResult
* ManualTestResult

According the xml-scheme these result-types share common elements from `TestResult`.
Specific elements aren't processed, it's more about to understand and read the elements from `<Result>`.

Fixes #74

### CODE REVIEW

**Comment by gfoidl** [comment]
@jsingh-qualitrol here you have a preview, please give it a try.

```bash
# deinstall current version
dotnet tool uninstall -g trx2junit

# install preview
dotnet tool install -g trx2junit --version 1.3.2-preview-1 --add-source https://pkgs.dev.azure.com/gh-gfoidl/github-Projects/_packaging/gfoidl-public/nuget/v3/index.json
```

**Comment by jsingh-qualitrol** [comment]
@gfoidl 
Just wanted to bring to your notice that when we try to do conversion, we get only TestSuite and not including Test cases which are grouped in each TestSuite. Do we have any way in which we can get Test Cases as well with TestSuite.

**Comment by gfoidl** [comment]
I can't follow what you mean. Can you show some simple examples to get a clear picture what your intention is?
Otherwise it's not actionable for me.

**Comment by jsingh-qualitrol** [comment]
[TestResults_trx.txt](https://github.com/gfoidl/trx2junit/files/4925530/TestResults_trx.txt)
[TestResults.txt](https://github.com/gfoidl/trx2junit/files/4925540/TestResults.txt)
The TestResult_trx.txt is having 43 TestSuite and 150 Test Cases, however we we convert it we get to see only 43 TestSuite and the testcases which are grouped in it are not converted. 
Hope this helps!

**Comment by gfoidl** [comment]
Just show some simple trx-xml here in the comments directly. No 150 Testcases. I don't want to dig through this. Keep it as simple as possible.

**Comment by jsingh-qualitrol** [comment]
Let me make it simple for you, now i have 1 Testsuite, which has 7 TestCases. Please have a look.
[TestResults.txt](https://github.com/gfoidl/trx2junit/files/4925679/TestResults.txt)
[TestResults_trx.txt](https://github.com/gfoidl/trx2junit/files/4925681/TestResults_trx.txt)

**Comment by gfoidl** [comment]
> simple for you

For me 1523 lines is not defined as simple 🤣, anyway.

Did you try https://github.com/gfoidl/trx2junit/pull/76#issuecomment-650802008?
With this version I'll get [TestResults.xml.txt](https://github.com/gfoidl/trx2junit/files/4925904/TestResults.xml.txt) which seems ok.

**Comment by jsingh-qualitrol** [comment]
I tried with version 1.3.2-preview-1 and i could see the Test Cases are shown here. Now i will run it in Jenkins to see the execution results are shown after Test are executed. Like Pass /Fail etc. 👍

**Comment by gfoidl** [comment]
While trying the larger sample (https://github.com/gfoidl/trx2junit/pull/76#issuecomment-658773014) I found another bug, which I'm fixing right now --> https://github.com/gfoidl/trx2junit/pull/77

**Comment by jsingh-qualitrol** [comment]
Please also ensure that we get Execution Status as well Like PASS/ FAIL/Not Executed / Skipped.

**Comment by gfoidl** [comment]
> Please also ensure that we get Execution Status as well Like PASS/ FAIL/Not Executed / Skipped.

Doesn't this show up?
I think according the [junit-scheme](https://github.com/gfoidl/trx2junit/blob/master/schemas/jenkins-junit.xsd) all relevant attributes are set. There is no value for pass or fail, as the reader has to deduce it from the test- and error-count.

**Comment by jsingh-qualitrol** [comment]
Hello @gfoidl ,

Today when i am converting the trx file i get error: 
image
[TestResult_new.txt](https://github.com/gfoidl/trx2junit/files/4931946/TestResult_new.txt)

**Comment by jsingh-qualitrol** [comment]
Yesterday, i was able to convert it successfully and today i get Object reference error. 
Please have a look. 
hope to hear from you soon.

**Comment by gfoidl** [comment]
Yeah, (unfortunately) I know this one --> see https://github.com/gfoidl/trx2junit/pull/76#issuecomment-658831401
I'll release a new preview, so you can test with this one. Just a few minutes...

**Comment by gfoidl** [comment]
@jsingh-qualitrol here you have a new preview, please give it a try.

```bash
# deinstall current version
dotnet tool uninstall -g trx2junit

# install preview
dotnet tool install -g trx2junit --version 1.3.2-preview-2 --add-source https://pkgs.dev.azure.com/gh-gfoidl/github-Projects/_packaging/gfoidl-public/nuget/v3/index.json
```

**Comment by jsingh-qualitrol** [comment]
Yes it is working fine now. 
Is it stable version to use on production machine?

**Comment by gfoidl** [comment]
> Yes it is working fine now.

Perfect 😄 

> Is it stable version to use on production machine?

Yes.
But I'll release a new version (not a preview version) is a moment. Just waited for your confirmation that it works.

**Comment by gfoidl** [comment]
--> https://github.com/gfoidl/trx2junit/releases/tag/v1.3.2 respectively https://www.nuget.org/packages/trx2junit/1.3.2

**Comment by jsingh-qualitrol** [comment]
Hello @gfoidl 
In trx file we usually notice that the classname is shown as fully qualified name as shown in pic 
image
And same is been converted as shown in xml file 
image

So i want to know from you can we trim the classname till its first comma and the extra info should not be getting converted in xml file. For eg : 
image

Please let me know about it.

**Comment by jsingh-qualitrol** [comment]
Hello @gfoidl 

Again we are getting error "Object reference to an instance":
image

Please have a look at it.

**Pull request merged**
