### PR TITLE
Fixed null-ref exception for Jenkins-trx input

### LINKED ISSUE #68: Null-Reference-Exception on Jenkins-trx input
See https://github.com/gfoidl/trx2junit/issues/9#issuecomment-639429455

@jsingh-qualitrol let's handle this here.

### PR DESCRIPTION
**Pull request by gfoidl**
Fixes https://github.com/gfoidl/trx2junit/issues/68

### CODE REVIEW

**Comment by gfoidl** [comment]
@jsingh-qualitrol please give it a try

```bash
# deinstall current version
dotnet tool uninstall -g trx2junit

# install preview
dotnet tool install -g trx2junit --version 1.3.1-preview-1 --add-source https://pkgs.dev.azure.com/gh-gfoidl/github-Projects/_packaging/gfoidl-public/nuget/v3/index.json
```

**Comment by jsingh-qualitrol** [comment]
@gfoidl  
I also tried to use by default MsTest plugin for conversion to xml file, although the output is xml but it is not in desired format of QMetry. 

I tried your latest release and it is converting xml file without any exception. Attached is the file with is converted 
[TestResults1.txt](https://github.com/gfoidl/trx2junit/files/4781878/TestResults1.txt)

And a sample file which QMetry is accepting is :
<?xml version="1.0" encoding="UTF-8"?>
<testsuite xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://maven.apache.org/surefire/maven-surefire-plugin/xsd/surefire-test-report.xsd" name="com.CalculatorTest" time="0.036" tests="5" errors="0" skipped="0" failures="1">
  <properties>
    <property name="sun.desktop" value="windows"/>
    <property name="file.encoding.pkg" value="sun.io"/>
    <property name="java.specification.version" value="1.8"/>
    <property name="java.vm.vendor" value="Oracle Corporation"/>
  </properties>
  <testcase name="testEqual" classname="com.CalculatorTest" time="0.007">
    <failure type="java.lang.AssertionError">java.lang.AssertionError
	at com.javacodegeeks.examples.junitmavenexample.CalculatorTest.testEqual11(CalculatorTest.java:59)
</failure>
    <system-out><![CDATA[This is executed before each Test
This is exceuted after each Test
]]></system-out>
  </testcase>
  <testcase name="testSum" classname="com.CalculatorTest" time="0"/>
  <testcase name="testSubstraction" classname="com.CalculatorTest" time="0.001"/>
  <testcase name="testDivisionException" classname="com.CalculatorTest" time="0"/>
  <testcase name="testDivison" classname="com.CalculatorTest" time="0"/>
</testsuite>

**Comment by gfoidl** [comment]
> tried your latest release and it is converting xml file without any exception

Fine, thanks for confirmation.

The attached TestResults1.txt looks quite empty?!

> And a sample file which QMetry is accepting is :

I can't follow... Is there any other problem? If so, please open a new issue, so this can be handled.

**Comment by jsingh-qualitrol** [comment]
@gfoidl 
I too noticed that the converted file is quite empty. 
And my need is to convert the file of trx and import it to QMetry  (addon to Jira). They provided some sample xml which they are supporting. 
Now, I need to make sure the converted file should be quite similar to QMetry file else it would not get imported. So, i shared it with you as the converted xml file was looking empty.

**Comment by gfoidl** [comment]
In the comment above I see just one attached file.

But please open a new issue if you feel that there needs to be taken some action for trx2junit.
I'm not aware of QMetry, but assume they provide a xml-schema, so trx2junit could be tweaked to emit output that validates against that schema.

**Comment by jsingh-qualitrol** [comment]
[JUnitSample.txt](https://github.com/gfoidl/trx2junit/files/4782613/JUnitSample.txt)
This is a sample xml which have been provided from QMetry. 

https://qmetrysupport.atlassian.net/wiki/spaces/QTM4J/pages/1000867047/Test+using+JUnit

**Comment by jsingh-qualitrol** [comment]
Hello @gfoidl 
Did you get a chance to look at above xml samples which i shared?
if trx2xml can include these details it would be great.

**Comment by gfoidl** [comment]
> But please open a new issue if you feel that there needs to be taken some action for trx2junit.

It's pure coincidence to monitor done issues, and can become quite messy to mix and match concerns.
So let's have separate items for each to work on.

**Pull request merged**
