### PR TITLE
net5

### PR DESCRIPTION
**Pull request by cheng93**
.NET 5 was released today!

### CODE REVIEW

**Comment by gfoidl** [comment]
@cheng93 thanks!

CI is not happy, as it AzP doesn't know about .NET 5. I'll merge this PR, fix CI then and release a new version.

**Comment by cheng93** [comment]
https://github.com/actions/virtual-environments/issues/1891

Looks like it'll be until Nov 16th before .NET 5 becomes available _by default_ on azure pipelines.

**Comment by gfoidl** [comment]
https://github.com/gfoidl/trx2junit/releases/tag/v1.4.0

@cheng93  thanks for this info.

**Pull request merged**
