### PR TITLE
Created standalone package of Core-logic and dropped .NET Core 2.1

### LINKED ISSUE #92: Release main library separately?
Hello and thank you so much for this project!

I was wondering if you had any interest in releasing the main code as a separate nuget package / library that could be integrated into other tools such as Nuke.Build? The separate tool requires one extra step to set up / maintain a build server. However, it works so well I don't mind doing it :)

My use case was that I wanted to simplify my unit test running so I have dotnet-vstest output a TRX file (so I don't need a custom logger). But Jenkins was taking 10+ minutes to ingest the TRX file. Converting it to Junit reduced the file size and the import time to a few seconds. Thanks again.

### PR DESCRIPTION
**Pull request by gfoidl**
* the core-logic is extracted into a new package `trx2junit.Core` which will be consumed by tool
* dropped support for .NET Core 2.1 as it reached end of life on 21.08.2021
* besides that only internal changes were done -- the usage of the tool _trx2junit_ won't be affected

Fixes https://github.com/gfoidl/trx2junit/issues/92

### CODE REVIEW

**Comment by gfoidl** [comment]
Ah, CI means
```
##[warning]No test result files matching tests/trx2junit.Tests/TestResults/*.trx were found.
```
🙈

**Comment by gfoidl** [comment]
@dstahl-axion here's my stab on it.

Please try it with the instructions below, and tell me if it fits your needs. Then I'd like to create a real release of it.

For the package see [trx2junit.Core v2.0.0-preview-1](https://dev.azure.com/gh-gfoidl/github-Projects/_packaging?_a=package&feed=gfoidl-public&package=trx2junit.Core&protocolType=NuGet&version=2.0.0-preview-1&view=overview)
The feed is `https://pkgs.dev.azure.com/gh-gfoidl/github-Projects/_packaging/gfoidl-public/nuget/v3/index.json` (more info in the link above).

For the tool:
```bash
# deinstall current version
dotnet tool uninstall -g trx2junit

# install preview
dotnet tool install -g trx2junit --version 2.0.0-preview-1 --add-source https://pkgs.dev.azure.com/gh-gfoidl/github-Projects/_packaging/gfoidl-public/nuget/v3/index.json
```

A bit a description is in the [ReadMe of the PR](https://github.com/gfoidl/trx2junit/blob/c4dc4af278367255ec9b62f5ac106f9fcd012aad/ReadMe.md#core-functionality-as-standalone-package-trx2junitcore).

**Comment by dstahl-axion** [comment]
@gfoidl Wow that was fast!

I've just tested these scenarios on two TRX files. One created from .net framework test assemblies and one created from .net5 test assemblies. I ran the latest published tool, the pre-release tool, and my own code using your trx2junit.Core nuget package.

All produced the same output after the same runtime.

This works exactly as I need it to and solves my needs perfectly. Thanks so much for the quick implementation!

**Comment by gfoidl** [comment]
You're welcome 😄 

Thanks for confirmation, so I'm going to make the official release.

**Pull request merged**
